Vagrant.configure("2") do |config|
 
  config.vm.box = "ubuntu/focal64"

  config.vm.hostname = "servidor-principal"

  config.vm.network "private_network", ip: "192.168.1.2"

  config.vm.network "forwarded_port", guest: 80, host: 8070
  
end